storage:
  file:
    path: "/path/to/storage/dir"

cache:
  type: "redis"
  addr: "ip_or_hostname:port"
  password: "your_redis_password"
  db_index: 0

model:
  embedding:
    api_url: "https://url/of/model"
    model_name: "name_of_model"
    api_key: "access_key_of_model"

  reranking:
    api_url: "https://url/of/model"
    model_name: "name_of_model"
    api_key: "access_key_of_model"

  llm:
    api_url: "https://url/of/model"
    model_name: "name_of_model"
    api_key: "access_key_of_model"